CREATE TABLE user_info(
	IDX INT NOT NULL AUTO_INCREMENT,
    USER_EMAIL VARCHAR(500) NOT NULL,
    USER_PW VARCHAR(500) NOT NULL,
    NICKNAME VARCHAR(200) NOT NULL,
    BIRTH DATE NOT NULL,
    USER_PROFILE LONGBLOB,
    C_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(IDX),
);